package com.thomsonreuters.wokmws.v3.woksearch;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.0
 * 2014-06-17T11:07:29.064+08:00
 * Generated source version: 3.0.0
 * 
 */
@WebServiceClient(name = "WokSearchService", 
                  wsdlLocation = "http://search.webofknowledge.com/esti/wokmws/ws/WokSearch?wsdl",
                  targetNamespace = "http://woksearch.v3.wokmws.thomsonreuters.com") 
public class WokSearchService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://woksearch.v3.wokmws.thomsonreuters.com", "WokSearchService");
    public final static QName WokSearchPort = new QName("http://woksearch.v3.wokmws.thomsonreuters.com", "WokSearchPort");
    static {
        URL url = null;
        try {
            url = new URL("http://search.webofknowledge.com/esti/wokmws/ws/WokSearch?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WokSearchService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://search.webofknowledge.com/esti/wokmws/ws/WokSearch?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WokSearchService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WokSearchService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WokSearchService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WokSearchService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WokSearchService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WokSearchService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns WokSearch
     */
    @WebEndpoint(name = "WokSearchPort")
    public WokSearch getWokSearchPort() {
        return super.getPort(WokSearchPort, WokSearch.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WokSearch
     */
    @WebEndpoint(name = "WokSearchPort")
    public WokSearch getWokSearchPort(WebServiceFeature... features) {
        return super.getPort(WokSearchPort, WokSearch.class, features);
    }

}
