package com.thomsonreuters.wokmws.v3.woksearchlite;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.0
 * 2014-06-17T11:08:49.866+08:00
 * Generated source version: 3.0.0
 * 
 */
@WebServiceClient(name = "WokSearchLiteService", 
                  wsdlLocation = "http://search.webofknowledge.com/esti/wokmws/ws/WokSearchLite?wsdl",
                  targetNamespace = "http://woksearchlite.v3.wokmws.thomsonreuters.com") 
public class WokSearchLiteService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://woksearchlite.v3.wokmws.thomsonreuters.com", "WokSearchLiteService");
    public final static QName WokSearchLitePort = new QName("http://woksearchlite.v3.wokmws.thomsonreuters.com", "WokSearchLitePort");
    static {
        URL url = null;
        try {
            url = new URL("http://search.webofknowledge.com/esti/wokmws/ws/WokSearchLite?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WokSearchLiteService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://search.webofknowledge.com/esti/wokmws/ws/WokSearchLite?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WokSearchLiteService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WokSearchLiteService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WokSearchLiteService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WokSearchLiteService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WokSearchLiteService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WokSearchLiteService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns WokSearchLite
     */
    @WebEndpoint(name = "WokSearchLitePort")
    public WokSearchLite getWokSearchLitePort() {
        return super.getPort(WokSearchLitePort, WokSearchLite.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WokSearchLite
     */
    @WebEndpoint(name = "WokSearchLitePort")
    public WokSearchLite getWokSearchLitePort(WebServiceFeature... features) {
        return super.getPort(WokSearchLitePort, WokSearchLite.class, features);
    }

}
