package com.thomsonreuters.wokmws.v3.woksearchlite;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.0
 * 2014-06-17T11:08:49.856+08:00
 * Generated source version: 3.0.0
 * 
 */
@WebService(targetNamespace = "http://woksearchlite.v3.wokmws.thomsonreuters.com", name = "WokSearchLite")
@XmlSeeAlso({ObjectFactory.class})
public interface WokSearchLite {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "retrieveById", targetNamespace = "http://woksearchlite.v3.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.v3.woksearchlite.RetrieveById")
    @WebMethod
    @ResponseWrapper(localName = "retrieveByIdResponse", targetNamespace = "http://woksearchlite.v3.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.v3.woksearchlite.RetrieveByIdResponse")
    public com.thomsonreuters.wokmws.v3.woksearchlite.SearchResults retrieveById(
        @WebParam(name = "databaseId", targetNamespace = "")
        java.lang.String databaseId,
        @WebParam(name = "uid", targetNamespace = "")
        java.util.List<java.lang.String> uid,
        @WebParam(name = "queryLanguage", targetNamespace = "")
        java.lang.String queryLanguage,
        @WebParam(name = "retrieveParameters", targetNamespace = "")
        com.thomsonreuters.wokmws.v3.woksearchlite.RetrieveParameters retrieveParameters
    ) throws QueryException_Exception, InternalServerException_Exception, AuthenticationException_Exception, SessionException_Exception, InvalidInputException_Exception, ESTIWSException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "retrieve", targetNamespace = "http://woksearchlite.v3.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.v3.woksearchlite.Retrieve")
    @WebMethod
    @ResponseWrapper(localName = "retrieveResponse", targetNamespace = "http://woksearchlite.v3.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.v3.woksearchlite.RetrieveResponse")
    public com.thomsonreuters.wokmws.v3.woksearchlite.SearchResults retrieve(
        @WebParam(name = "queryId", targetNamespace = "")
        java.lang.String queryId,
        @WebParam(name = "retrieveParameters", targetNamespace = "")
        com.thomsonreuters.wokmws.v3.woksearchlite.RetrieveParameters retrieveParameters
    ) throws QueryException_Exception, InternalServerException_Exception, AuthenticationException_Exception, SessionException_Exception, InvalidInputException_Exception, ESTIWSException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "search", targetNamespace = "http://woksearchlite.v3.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.v3.woksearchlite.Search")
    @WebMethod
    @ResponseWrapper(localName = "searchResponse", targetNamespace = "http://woksearchlite.v3.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.v3.woksearchlite.SearchResponse")
    public com.thomsonreuters.wokmws.v3.woksearchlite.SearchResults search(
        @WebParam(name = "queryParameters", targetNamespace = "")
        com.thomsonreuters.wokmws.v3.woksearchlite.QueryParameters queryParameters,
        @WebParam(name = "retrieveParameters", targetNamespace = "")
        com.thomsonreuters.wokmws.v3.woksearchlite.RetrieveParameters retrieveParameters
    ) throws QueryException_Exception, InternalServerException_Exception, AuthenticationException_Exception, SessionException_Exception, InvalidInputException_Exception, ESTIWSException_Exception;
}
