
package com.thomsonreuters.wokmws.cxf.auth;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.0
 * 2014-06-17T11:04:19.544+08:00
 * Generated source version: 3.0.0
 */

@WebFault(name = "AuthenticationException", targetNamespace = "http://auth.cxf.wokmws.thomsonreuters.com")
public class AuthenticationException_Exception extends Exception {
    
    private com.thomsonreuters.wokmws.cxf.auth.AuthenticationException authenticationException;

    public AuthenticationException_Exception() {
        super();
    }
    
    public AuthenticationException_Exception(String message) {
        super(message);
    }
    
    public AuthenticationException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public AuthenticationException_Exception(String message, com.thomsonreuters.wokmws.cxf.auth.AuthenticationException authenticationException) {
        super(message);
        this.authenticationException = authenticationException;
    }

    public AuthenticationException_Exception(String message, com.thomsonreuters.wokmws.cxf.auth.AuthenticationException authenticationException, Throwable cause) {
        super(message, cause);
        this.authenticationException = authenticationException;
    }

    public com.thomsonreuters.wokmws.cxf.auth.AuthenticationException getFaultInfo() {
        return this.authenticationException;
    }
}
