
package com.thomsonreuters.wokmws.cxf.auth;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.0
 * 2014-06-17T11:04:19.553+08:00
 * Generated source version: 3.0.0
 */

@WebFault(name = "ESTIWSException", targetNamespace = "http://auth.cxf.wokmws.thomsonreuters.com")
public class ESTIWSException_Exception extends Exception {
    
    private com.thomsonreuters.wokmws.cxf.auth.ESTIWSException estiwsException;

    public ESTIWSException_Exception() {
        super();
    }
    
    public ESTIWSException_Exception(String message) {
        super(message);
    }
    
    public ESTIWSException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ESTIWSException_Exception(String message, com.thomsonreuters.wokmws.cxf.auth.ESTIWSException estiwsException) {
        super(message);
        this.estiwsException = estiwsException;
    }

    public ESTIWSException_Exception(String message, com.thomsonreuters.wokmws.cxf.auth.ESTIWSException estiwsException, Throwable cause) {
        super(message, cause);
        this.estiwsException = estiwsException;
    }

    public com.thomsonreuters.wokmws.cxf.auth.ESTIWSException getFaultInfo() {
        return this.estiwsException;
    }
}
