package com.thomsonreuters.wokmws.cxf.auth;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.0
 * 2014-06-17T11:04:19.590+08:00
 * Generated source version: 3.0.0
 * 
 */
@WebServiceClient(name = "WOKMWSAuthenticateService", 
                  wsdlLocation = "http://search.webofknowledge.com/esti/wokmws/ws/WOKMWSAuthenticate?wsdl",
                  targetNamespace = "http://auth.cxf.wokmws.thomsonreuters.com") 
public class WOKMWSAuthenticateService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://auth.cxf.wokmws.thomsonreuters.com", "WOKMWSAuthenticateService");
    public final static QName WOKMWSAuthenticatePort = new QName("http://auth.cxf.wokmws.thomsonreuters.com", "WOKMWSAuthenticatePort");
    static {
        URL url = null;
        try {
            url = new URL("http://search.webofknowledge.com/esti/wokmws/ws/WOKMWSAuthenticate?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WOKMWSAuthenticateService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://search.webofknowledge.com/esti/wokmws/ws/WOKMWSAuthenticate?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WOKMWSAuthenticateService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WOKMWSAuthenticateService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WOKMWSAuthenticateService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WOKMWSAuthenticateService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WOKMWSAuthenticateService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WOKMWSAuthenticateService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns WOKMWSAuthenticate
     */
    @WebEndpoint(name = "WOKMWSAuthenticatePort")
    public WOKMWSAuthenticate getWOKMWSAuthenticatePort() {
        return super.getPort(WOKMWSAuthenticatePort, WOKMWSAuthenticate.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WOKMWSAuthenticate
     */
    @WebEndpoint(name = "WOKMWSAuthenticatePort")
    public WOKMWSAuthenticate getWOKMWSAuthenticatePort(WebServiceFeature... features) {
        return super.getPort(WOKMWSAuthenticatePort, WOKMWSAuthenticate.class, features);
    }

}
